version: 2.1
executors:
  infrastructure_container:
    docker:
      - image: aeternity/infrastructure:Split-terraform-modules-in-separate-repos-PT-165295661
    working_directory: /infrastructure

commands:
  integration_tests:
    description: "Integration Tests"
    steps:
      - run:
          name: Integration Tests
          command: |
            make integration-tests TF_VAR_envid="tf_test_${CIRCLE_JOB}_${CIRCLE_SHA1}"
      - run:
          name: Integration env cleanup
          command: |
            make integration-tests-cleanup TF_VAR_envid="tf_test_${CIRCLE_JOB}_${CIRCLE_SHA1}"
          when: on_fail

  setup_secrets:
    steps:
      - run:
          name: Setup Environment
          command: echo "source import-secrets.sh" >> $BASH_ENV

jobs:
  validate:
    executor: infrastructure_container
    steps:
      - setup_secrets
      - run:
          name: Validate Terraform environments
          command: |
            make terraform-validate-environments

  # Checks the compatibility of latest package build and master bootstrap
  integration_tests:
    executor: infrastructure_container
    steps:
      - setup_secrets
      - integration_tests

workflows:
  test:
    jobs:
      - validate:
          context: ae-infra-manage
          requires: []

      - integration_tests:
          context: ae-infra-manage
          requires:
            - validate

