version: 2.1
executors:
  infrastructure_container:
    docker:
      - image: aeternity/infrastructure:Split-terraform-modules-in-separate-repos-PT-165295661
    working_directory: /src

commands:
  integration_tests:
    description: "Integration Tests"
    steps:
      - run:
          name: Integration Tests
          command: |
            export TF_VAR_envid="tf_test_${CIRCLE_JOB}_${CIRCLE_SHA1}"
            cd test && terraform init && terraform apply -parallelism=20 --auto-approve
            cd /infrastructure/ansible && ansible-playbook health-check.yml --limit=tag_envid_${TF_VAR_envid} -e env=test
      - run:
          name: Integration env cleanup
          command: |
            export TF_VAR_envid="tf_test_${CIRCLE_JOB}_${CIRCLE_SHA1}"
            cd test && terraform destroy -parallelism=20 --auto-approve
          when: always

  setup_secrets:
    steps:
      - run:
          name: Setup Environment
          command: echo "source /infrastructure/import-secrets.sh" >> $BASH_ENV

jobs:
  validate:
    executor: infrastructure_container
    steps:
      - checkout
      - setup_secrets
      - run:
          name: Validate Terraform environments
          command: |
            cd terraform/environments && terraform init && terraform validate && terraform fmt -check=true -diff=true

  # Checks the compatibility of latest package build and master bootstrap
  integration_tests:
    executor: infrastructure_container
    steps:
      - checkout
      - setup_secrets
      - integration_tests

workflows:
  test:
    jobs:
      - validate:
          context: ae-infra-manage
          requires: []

      - integration_tests:
          context: ae-infra-manage
          requires:
            - validate

